Fix build by using proper SLUMBER_API_HOST
The api_host used in SLUMBER_API_HOST needs to point to the
proxied instance otherwise it fails:
slumber.exceptions.HttpNotFoundError: Client Error 404: http://localhost:8002/api/v2/project/29/

And possibly does not regress d0ff2e435a19c1535dbdd886ed1e512374d8fedd
which fixed the build because slumber client was not following
nginx http -> https redirect.