app: add missing vew version permission to api consumer user
While at it decouple the user creation from the permissions
granting. We want to create the user once but better
fixup permissions at each deploy.

Fixes:
ERROR An unhandled exception was raised during build setup [readthedocs.projects.tasks:329]
Traceback (most recent call last):
  File "/readthedocs/projects/tasks.py", line 314, in run
    self.version = self.get_version(self.project, version_pk)
  File "/readthedocs/projects/tasks.py", line 84, in get_version
    version_data = api_v2.version(version_pk).get()
  File "/virtualenv/lib/python3.5/site-packages/slumber/__init__.py", line 155, in get
    resp = self._request("GET", params=kwargs)
  File "/virtualenv/lib/python3.5/site-packages/slumber/__init__.py", line 101, in _request
    raise exception_class("Client Error %s: %s" % (resp.status_code, url), response=resp, content=resp.content)
slumber.exceptions.HttpNotFoundError: Client Error 404: http://localhost:8002/api/v2/version/1025/